Zadanie 6.4 ver1
se1ryu/piotr-mizer-kodilla-java pull request #8
Opened 2018-03-16 21:30 UTC by se1ryu

Strasznie duzo klopotu sprawia mi to zadanie, mam problem z tym ze jestem ograniczony metodami z zadania. Np, w moich testach chcialbym pozniej sprwadzic czy arraylista utworzona w ShapeCollector wynosi 0 po usunieciu jedynego elementu, ale nie wiem jak to zrobic bez stworzenia kolejnej metody.

Zastanawiam sie czy tez 2 testy ktore stworzylem sa wystarczajace, czy tez powinien byc test oddzielnie na samo getFigure? Uzywalem getFigure  w pierwszym tescie wiec nie jestem pewny.

Dodatkowo pytanie, w zadaniu napisane jest zeby klasa ShapeCollector miala 3 metody:

"Klasa ShapeCollector ma trzy metody:
jedną dodającą figurę do kolekcji,
drugą usuwającą figurę z kolekcji,
trzecią pobierającą z kolekcji figurę z pozycji n listy."

A potem w podpunkcie 4 sa opisane 4 metody: 

"Utwórz klasę ShapeCollector, z metodami: addFigure(Shape shape), removeFigure(Shape shape), getFigure(int n) oraz showFigures()"

koniec koncow stworzylem metode showFigures ale jej nie zamiescilem do testow bo nie jestem pewny po co mi ona wlasciwie ani co mialaby robic.

Dzieki z gory za pomoc :)

2018-03-17 08:37 UTC, MARudnicki commented
faktycznie tresc zadania zostawia sporo domyslom. Podpowiem Ci rozwiazanie wiekszosci kursantow. Zapisz metode showFigures jako getter
```
    public List<Shape> showFigures(){
        return shapeList;
    }
```

2018-03-17 08:39 UTC, MARudnicki requested changes

2018-03-17 08:39 UTC, MARudnicki commented on kodilla-testing/src/main/java/com/kodilla/testing/shape/ShapeCollector.java
> +        return result;
shapeList.remove(shape) zwraca booleana i robi to samo co twoja metoda, tzn,
```
    public boolean removeFigure(Shape shape) {
        return shapeList.remove(shape);
    }
```
bedzie robila dokladnie to samo

2018-03-17 08:39 UTC, MARudnicki commented on kodilla-testing/src/main/java/com/kodilla/testing/shape/ShapeCollector.java
> +    Shape shape;
czy ten shape jest do czegos potrzebny ?

2018-03-17 08:39 UTC, MARudnicki commented on kodilla-testing/src/main/java/com/kodilla/testing/shape/ShapeCollector.java
> +    public ArrayList<Shape> shapeList = new ArrayList<Shape>();
zmien na private

2018-03-17 08:42 UTC, MARudnicki requested changes

2018-03-17 08:42 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/shape/ShapeCollectorTestSuite.java
> +        Assert.assertTrue(result);
test remove jest niewystarczajacy. Powinien sprawdzac czy po usunieciu elementu faktycnznie nie ma w kolekcji
przykladowy scenaiusz
- dodaj element
- usun element
- spradz (przy uzyciu showFigures) czy kolekcja jest pusta

2018-03-18 17:21 UTC, se1ryu commented
Dzieki za pomoc, nanioslem poprawki :)

2018-03-19 07:23 UTC, MARudnicki requested changes

2018-03-19 07:23 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/shape/ShapeCollectorTestSuite.java
> +        Assert.assertEquals(0, shapeCollector.getShapeList());
powinno byc
`Assert.assertEquals(0, shapeCollector.getShapeList().size())`

2018-03-19 18:33 UTC, se1ryu commented
Poprawione.

2018-03-19 19:57 UTC, merged