6.5 Zadanie
se1ryu/piotr-mizer-kodilla-java pull request #9
Opened 2018-03-19 18:32 UTC by se1ryu

Nameczylem sie z tym okrutnie, mam nadzieje ze w miare spoko.

2018-03-19 19:41 UTC, MARudnicki reviewed
Brakuje wpisu w gradle.build w tym module o dependency do mockito

2018-03-19 19:51 UTC, MARudnicki requested changes

2018-03-19 19:51 UTC, MARudnicki commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/ForumStat.java
> +    }
tataj sa 2 bledy
1) dla postCount = 10 i userNamesQauntity = 0, twoj algorytm da wynik 0. 10/0 daje nieskaczonosc, nie 0.
zmien typ averageUserPost na Double i java poda wynik == Infinity
2) int/int daje int'a ktory nastepnie jest przypisywany do doubla juz po zaokragleniu do liczby calkowitej
uzyj zapisu np. 
` averageUserPost = (double)postsCount / userNamesQuantity;`
double / int daje double - java rzutuje oba typy do doubla, nastepnie wykonuje obliczenia ktore dadza poprawny, zmiennoprzecinkowy wynik

2018-03-19 19:51 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/forum/statistics/ForumStatisticsTestSuite.java
> +        ArrayList<String> forumUsers = new ArrayList<String>();
dobra praktyka jest zapis
```
List<String> forumUsers = new ArrayList<String>();

2018-03-20 20:49 UTC, se1ryu commented
Nanioslem poprawki

2018-03-22 17:58 UTC, merged